### ISSUE TITLE
Can't get 1.5.1 working on Lion 10.7.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libnfc#184]
```
What steps will reproduce the problem?
1. ./configure
2. make
3.

What is the expected output? What do you see instead?
Expected: Normal ./configure  -  make  -  make install    process.

Instead:

make  all-recursive
Making all in libnfc
Making all in chips
  CC     libnfcchips_la-pn53x.lo
pn53x.c:2372:63: warning: ISO C99 requires rest arguments to be used
pn53x.c:2377:71: warning: ISO C99 requires rest arguments to be used
pn53x.c:2386:77: warning: ISO C99 requires rest arguments to be used
  CCLD   libnfcchips.la
Making all in buses
  CC     libnfcbuses_la-uart.lo
In file included from uart.c:38:
uart_posix.c:295:60: warning: ISO C99 requires rest arguments to be used
uart_posix.c:301:58: warning: ISO C99 requires rest arguments to be used
  CCLD   libnfcbuses.la
Making all in drivers
  CC     libnfcdrivers_la-acr122.lo
In file included from acr122.c:41:
/System/Library/Frameworks/PCSC.framework/Headers/winscard.h:90: error: 
expected declaration specifiers or ‘...’ before ‘LPSCARD_READERSTATE_A’
make[3]: *** [libnfcdrivers_la-acr122.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2



What version of the product are you using? On what operating system?
I'm trying to install 1.5.1 on Lion 10.7.2


Please provide any additional information below.

```

Original issue reported on code.google.com by `jonathan...@gmail.com` on 13 Jan 2012 at 7:12
